### ISSUE TITLE
Pale Wood Compatability

### ISSUE THREAD

**Issue by Yo-Snowpro** [NemoNotFound/NemosWoodcutter#1]
Add in pale wood compatability in 1.21.3

**Comment by NemoNotFound** [comment]
I removed it from 1.21.3 again, since a lot of errors were shown in the logs. Might add it again soon, once I figure out, how to fix this

**Comment by Yo-Snowpro** [comment]
Sounds good :D

**Comment by NemoNotFound** [comment]
It's included in 1.21.4, do you need it for 1.21.3?
