### ISSUE TITLE
Recipes!

### ISSUE THREAD

**Issue by Nitroito** [NemoNotFound/NemosWoodcutter#1]
recipes seem  to craft twice as normal...

1 log => 4 doors
1 log => 8 trapdoors
1 log => 4 fences
1 log => 4 fence gates

and so on...

Regards

**Comment by NemoNotFound** [comment]
Hey, that's normal behaviour!
From 1 log, you get 4 planks. wiht 2 planks you get two doors, with one plank 4 fences and so on.
So 1 log returns what a plank would return times 4. If a recipe needs two planks to craft, then it's divided by two.
e.g. door needs two planks to craft two doors, so 1 log = 4 planks = 4 doors

**Comment by Nitroito** [comment]
You my be mistaken... Taking the doors as example... vanilla minecraft from
6 planks you get 3 doors, so 2 planks you get 1 door... 1 log 4 doors...

**Comment by NemoNotFound** [comment]
The Woodcutter is there to be more efficient, exactly how the stonecutter works. There you also get 1 stair out of 1 stone, instead of 6 stones. Same here. You get two doors out of two planks, instead of 3 out of 6

**Comment by NemoNotFound** [comment]
Since this is expected behaviour and there was no new comment, I'll close this ticket
