### ISSUE TITLE
Woodcutter not making pale wood planks into slabs ,stairs, fences, fence gates, trap doors, etc. 

### ISSUE THREAD

**Issue by TheDarkPanther** [NemoNotFound/NemosWoodcutter#5]
It only seems to make these blocks:
![2024-10-29_15 22 06](https://github.com/user-attachments/assets/ba92a818-6169-49a3-a2e8-bda21647bc08)

**Comment by NemoNotFound** [comment]
It's not an issue, the pale wood planks are experimental, so I didn't add the recipes for them yet. Will do it soon though.

Will close this ticket and let you know once I updated it :D

**Comment by NemoNotFound** [comment]
Or let me reopen it, to keep it as reminder haha

**Comment by NemoNotFound** [comment]
I've added the recipes in nemo's Woodcutter 1.12. Will close this ticket, hope you'll like the mod!
